<?php $this->layout('layout::default', ['title' => $title]) ?>

<?php $this->start('scripts') ?>
    <script>
        $(document).ready(function () {
            window.app.fn.initMapChoose();
        });
    </script>
<?php $this->stop() ?>

<div class="container">
    <h1><?=$this->translate('Geocode')?>: <?=$this->translate('Choose the correct result')?></h1>
    <hr>
    <dl>
        <dt><?=$this->translate('Table')?></dt>
        <dd><?=$this->e($table)?></dd>
    </dl>
    <hr>
    <div class="row align-items-center">
        <div class="col">
            <div class="text-primary">
                <strong><?=$this->translate('Address')?></strong>:
                <?=$this->e($address)?><br>
                <i class="fas fa-arrow-right"></i>
                <span id="selection"></span>
            </div>
        </div>
        <div class="col text-right">
            <a href="#" class="btn btn-primary disabled" data-id="<?=$id?>" id="btn-save"><i class="fas fa-save"></i> <?=$this->translate('Save')?></a>
            <a href="?skip=<?=$this->e($id)?>" class="btn btn-outline-danger"><?=$this->translate('Skip')?> <i class="fas fa-angle-double-right"></i></a>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col" id="results">
            <?php foreach ($results as $provider => $addresses) : ?>
            <div data-provider="<?=$provider?>">
                <h2><i class="fas fa-map-marker-alt"></i> <?=$this->translate($provider)?></h2>
                <ul>
                    <?php foreach ($addresses as $i => $addr) : ?>
                        <li data-longitude="<?=$addr['longitude']?>" data-latitude="<?=$addr['latitude']?>" data-id="<?=$id?>" data-address="<?=$i?>">
                            <?=$this->e($addr['address'])?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <?php endforeach; ?>
        </div>
        <div class="col">
            <div id="map" style="height: 100%;"></div>
        </div>
    </div>
</div>
