<?php $this->layout('layout::default', ['title' => $title, 'version' => $version]) ?>

<div class="container">
    <h1><?=$this->translate($title)?></h1>
    <p>
        <?=$this->translate('The <em>Batch Geocoder</em> application allows you to geocode your dataset of addresses.')?><br>
        <?=$this->translate('You can upload your file and the application will process it to add a location (longitude, latitude) to each address.')?><br>
    </p>
    <hr>
    <h2><?=$this->translate('Data structure')?></h2>
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            <table class="table table-sm">
                <tr><th><?=$this->translate('Identifier')?></th><td class="text-info"><em>string</em></td><td><?=$this->translate('Must be unique')?></td></tr>
                <tr><th><?=$this->translate('Streetname')?></th><td class="text-info"><em>string</em></td><td></td></tr>
                <tr><th><?=$this->translate('House number')?></th><td class="text-info"><em>string</em></td><td></td></tr>
                <tr><th><?=$this->translate('Postal code')?></th><td class="text-info"><em>integer</em></td><td></td></tr>
                <tr><th><?=$this->translate('Locality')?></th><td class="text-info"><em>string</em></td><td></td></tr>
            </table>
        </div>
    </div>
    <hr>
    <div class="row justify-content-md-center">
        <div class="col-md-6">
            <?php if (!is_null($error)): ?>
                <div class="alert alert-danger">
                    <strong><?=$this->translate('An error occured :')?></strong><br>
                    <?=$error?>
                </div>
            <?php endif ?>
            <form id="geocoder-form" action="./upload" method="post" autocomplete="off" enctype="multipart/form-data">
                <p class="form-text">
                    <?=$this->translate('You can upload a <code>.txt</code> or <code>.csv</code> file. Your file must be UTF-8 encoded and the separator must be a comma <kbd>,</kbd>. Your file must not have a header.')?>
                </p>
                <?php if (!is_null($limit)): ?>
                    <p class="form-text">
                        <?=$this->translate('Maximum count of records')?>: <?=$limit?>
                    </p>
                <?php endif ?>
                <div class="form-group">
                    <input type="file" name="file" class="form-control-file" accept=".csv,.txt" required="required">
                    <small id="passwordHelpBlock" class="form-text text-muted">
                        <?=$this->translate('Your data will be completely removed from our server at the latest after 24 hours !')?>
                    </small>
                </div>
                <button type="submit" class="btn btn-primary btn-block mt-3"><i class="fa fa-upload"></i> <?=$this->translate('Send')?></button>
            </form>
        </div>
    </div>
    <?php if ($archives === true): ?>
        <hr>
        <div class="row justify-content-md-center">
            <div class="col-md-6">
                <form id="geocoder-archives-form" action="./validate" method="post" autocomplete="off">
                    <div class="form-group">
                        <label for="selectArchives" class="font-weight-bold"><i class="fas fa-archive"></i> <?=$this->translate('Archives')?></label>
                        <select name="table" id="selectArchives" class="form-control">
                            <?php foreach ($tables as $t): ?>
                                <option value="<?=$t?>"><?=$t?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block mt-3"><?=$this->translate('Load')?></button>
                </form>
            </div>
        </div>
    <?php endif ?>
</div>
