<?php $this->layout('layout::default', []) ?>

<div class="container">
    <h1><?=$this->translate('Validate')?></h1>
    <hr>
    <dl>
        <dt><?=$this->translate('Table')?></dt>
        <dd><?=$this->e($table)?></dd>
    </dl>
    <hr>

    <p>
        <?=$this->translate('The application try to validate matching between postal code and locality.')?>
        <?=$this->translate('If there is no valid match between the postal code and the locality of one of your addresses, the application provides you suggestion to fix it.')?><br>
        <?=$this->translate('You can skip an invalid address (or all of it) but all the invalid addresses will not be geocoded !')?>
    </p>

    <hr>

    <form action="./validate" method="post">
        <table class="table table-striped">
            <tbody>
            <?php foreach ($suggestions as $postalcode => $suggest): ?>
                <?php foreach ($suggest as $locality => $sugg): ?>
                    <tr>
                        <td class="align-middle"><?=$postalcode?></td>
                        <td class="align-middle"><?=$locality?></td>
                        <td>
                            <select class="form-control" name="validate[<?=$postalcode?>][<?=$locality?>]">
                            <?php foreach ($sugg as $s): ?>
                                <option value="<?=$s['postalcode']?>|<?=$s['name']?>"><?=$s['postalcode']?> - <?=$s['name']?></option>
                            <?php endforeach ?>
                            </select>
                        </td>
                        <td class="text-center">
                            <button type="button" class="btn btn-warning btn-skip-validation">
                                <i class="far fa-times-circle"></i>
                                <?=$this->translate('Skip')?>
                            </button>
                        </td>
                    </tr>
                <?php endforeach ?>
            <?php endforeach ?>
            </tbody>
        </table>
        <div class="row justify-content-md-center">
            <div class="col-md-6 text-center">
                <button type="submit" class="btn btn-primary" name="action" value="validate">
                    <i class="far fa-check-circle"></i>
                    <?=$this->translate('Save')?>
                </button>
                <a href="./geocode" class="btn btn-danger">
                    <i class="far fa-times-circle"></i>
                    <?=$this->translate('Skip all')?>
                </a>
            </div>
        </div>
    </form>
</div>
