<?php $this->layout('layout::default', []) ?>

<div class="container">
    <div class="float-right">
        <a href="<?=$this->url('map')?>" class="btn btn-lg btn-outline-secondary" style="text-decoration: none;">
            <i class="far fa-map"></i>
            <?=$this->translate('Map')?>
        </a>
        <div class="btn-group">
            <button class="btn btn-lg btn-outline-primary dropdown-toggle" type="button" id="dropExport" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-download"></i>
                <?=$this->translate('Export')?>
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropExport">
                <a class="dropdown-item" href="<?=$this->url('export', ['type' => 'csv'])?>">CSV</a>
                <a class="dropdown-item" href="<?=$this->url('export', ['type' => 'geojson'])?>">GeoJSON</a>
                <a class="dropdown-item" href="<?=$this->url('export', ['type' => 'xlsx'])?>">XLSX</a>
            </div>
        </div>
    </div>
    <h1>
        <?=$this->translate('Results')?>
    </h1>
    <hr>
    <ul class="nav nav-tabs" id="tabs" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="tab-geocoded" data-toggle="tab" href="#geocoded" role="tab" aria-controls="home" aria-selected="true">
                <i class="far fa-list-alt text-success"></i>
                <?=$this->translate('Geocoded')?>
                <span class="badge badge-pill badge-light"><?=count($addressGeocoded)?></span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="tab-notgeocoded" data-toggle="tab" href="#notgeocoded" role="tab" aria-controls="profile" aria-selected="false">
                <i class="far fa-list-alt text-warning"></i>
                <?=$this->translate('Not geocoded')?>
                <span class="badge badge-pill badge-light"><?=count($addressNotGeocoded)?></span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="tab-invalid" data-toggle="tab" href="#invalid" role="tab" aria-controls="contact" aria-selected="false">
                <i class="far fa-list-alt text-danger"></i>
                <?=$this->translate('Invalid')?>
                <span class="badge badge-pill badge-light"><?=count($addressInvalid)?></span>
            </a>
        </li>
    </ul>
    <div class="tab-content" id="tabs-content">
        <div class="tab-pane fade show active" id="geocoded" role="tabpanel" aria-labelledby="tab-geocoded">
            <table class="mt-3 table table-striped table-sm">
                <thead>
                    <tr>
                        <th><?=$this->translate('Source address')?></th>
                        <th><?=$this->translate('Geocoded address')?></th>
                        <th><?=$this->translate('Score')?></th>
                        <th><?=$this->translate('Provider')?></th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($addressGeocoded as $address): ?>
                    <tr>
                        <td><?=$address[1]?></td>
                        <td><?=$address[2]?></td>
                        <td class="text-center text-nowrap">
                            <?php for ($i = 0; $i < $address[3]; $i++): ?><i class="fas fa-star"></i><?php endfor ?><?php for ($i = $address[3]; $i < 4; $i++): ?><i class="far fa-star"></i><?php endfor ?>
                        </td>
                        <td class="text-center text-nowrap">
                            <span class="badge badge-light"><?=$address[0]?></span>
                            <?php if ($address[4] === true): ?>
                                <span class="badge badge-light"><i class="fas fa-user"></i></span>
                            <?php endif ?>
                        </td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>
        <div class="tab-pane fade" id="notgeocoded" role="tabpanel" aria-labelledby="tab-notgeocoded">
            <ul class="mt-3">
                <?php foreach ($addressNotGeocoded as $address): ?>
                    <li><?=$address?></li>
                <?php endforeach ?>
            </ul>
        </div>
        <div class="tab-pane fade" id="invalid" role="tabpanel" aria-labelledby="tab-invalid">
            <ul class="mt-3">
                <?php foreach ($addressInvalid as $address): ?>
                    <li><?=$address?></li>
                <?php endforeach ?>
            </ul>
        </div>
    </div>
</div>
