<footer class="footer bg-light text-muted">
    <div class="container">
        <div class="row">
            <div class="col-auto mr-auto">
                &copy; <?=date('Y')?> <a href="https://geo6.be/" target="_blank">GEO-6</a>
            </div>
            <div class="col-auto">
                <div class="btn-group dropup">
                    <button type="button" class="btn btn-light btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="far fa-language"></i>
                        <?=ucfirst(Locale::getDisplayLanguage(Locale::getDefault()))?>
                    </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="?<?=http_build_query(array_merge($params ?? [], ['lang' => 'fr']))?>">Fran&ccedil;ais</a>
                        <a class="dropdown-item" href="?<?=http_build_query(array_merge($params ?? [], ['lang' => 'nl']))?>">Nederlands</a>
                        <a class="dropdown-item" href="?<?=http_build_query(array_merge($params ?? [], ['lang' => 'en']))?>">English</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
