<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
  <div class="container d-flex justify-content-between">
    <a class="navbar-brand" href="<?=$this->url('home')?>"><?=$this->e($title)?></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
<?php if (isset($navbar)): ?>
        <ul class="navbar-nav mr-auto">
<?php foreach($navbar as $navbarLink): ?>
          <li class="nav-item">
            <a class="nav-link" href="<?=$this->e($navbarLink->link)?>"><?=$this->e($navbarLink->title)?></a>
          </li>
<?php endforeach ?>
        </ul>
<?php endif ?>
    </div>
  </div>
</nav>
