<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
  <div class="container d-flex justify-content-between">
    <a class="navbar-brand" href="<?=$this->url('home')?>"><?=$this->e($title)?></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownLanguage" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-language"></i>
                    <?=ucfirst(Locale::getDisplayLanguage(Locale::getDefault()))?>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownLanguage">
                    <a class="dropdown-item" href="?<?=http_build_query(array_merge($params ?? [], ['lang' => 'fr']))?>">Fran&ccedil;ais</a>
                    <a class="dropdown-item" href="?<?=http_build_query(array_merge($params ?? [], ['lang' => 'nl']))?>">Nederlands</a>
                    <a class="dropdown-item" href="?<?=http_build_query(array_merge($params ?? [], ['lang' => 'en']))?>">English</a>
                </div>
            </li>
            <?php if (isset($identity)): ?>
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" id="navbarDropdownIdentity" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user-circle" title="<?=$identity?>"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownIdentity">
                    <a class="dropdown-item" href="<?=$this->url('logout')?>">
                        <i class="fas fa-sign-out-alt"></i>
                        <?=$this->translate('Log out')?>
                    </a>
                </div>
            </li>
            <?php endif ?>
        </ul>
    </div>
  </div>
</nav>
