<div id="geocoder-modal-info" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">
                    <i class="far fa-question-circle"></i>
                    <?=$this->translate('About')?>
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
            <?php if (isset($providersAutomatic, $providersManual)) : ?>
                <strong><?=$this->translate('Providers in automatic mode')?>:</strong>
                <ol>
                <?php foreach ($providersAutomatic as $p): ?>
                    <li><?=$this->e($p)?></li>
                <?php endforeach ?>
                </ol>
                <strong><?=$this->translate('Providers in interactive mode')?>:</strong>
                <ol>
                <?php foreach ($providersManual as $p): ?>
                    <li><?=$this->e($p)?></li>
                <?php endforeach ?>
                </ol>
            <?php else : ?>
                <strong><?=$this->translate('Providers')?>:</strong>
                <ol>
                <?php foreach ($providers as $p): ?>
                    <li><?=$this->e($p)?></li>
                <?php endforeach ?>
                </ol>
            <?php endif ?>
                <hr>
                <p class="small text-info">
                    <i class="fab fa-github"></i>
                    <a href="https://github.com/geo6/batch-geocoder/" target="_blank"><?=$this->translate('Submit issue, or suggestion on GitHub')?></a>
                </p>
            </div>
        </div>
    </div>
</div>
